<?php

    return [
        // [
        //     'title' => 'Dashboards',
        //     'icon' => 'tabler-smart-home',
        //     'route' => 'dashboard.index',
        //     'active' => 'dashboard',
        //     'sort' => 1,
        //     'roles' => [1],
        // ],
        [
            'title' => 'User',
            'icon' => 'tabler-users-group',
            'route' => 'dashboard.user.index',
            'active' => 'dashboard.user.index',
            'sort' => 1,
            'roles' => [1],
        ],
        [
            'title' => 'Floors',
            'icon' => 'tabler-building',
            'route' => 'dashboard.floor.index',
            'active' => 'dashboard.floor.index',
            'sort' => 2,
            'roles' => [1],
        ],
        [
            'title' => 'Services',
            'icon' => 'tabler-building-community',
            'route' => 'dashboard.service.index',
            'active' => 'dashboard.service.index',
            'sort' => 5,
            'roles' => [1],
        ],
        [
            'title' => 'Spaces',
            'icon' => 'tabler-spaces',
            'route' => 'dashboard.space.index',
            'active' => 'dashboard.space.index',
            'sort' => 5,
            'roles' => [1],
        ],
        [
            'title' => 'Space Types',
            'icon' => 'tabler-briefcase',
            'route' => 'dashboard.spacetype.index',
            'active' => 'dashboard.spacetype.index',
            'sort' => 6,
            'roles' => [1],
        ],
        [
            'title' => 'Amenities',
            'icon' => 'tabler-building-community',
            'route' => 'dashboard.amenities.index',
            'active' => 'dashboard.amenities.index',
            'sort' => 7,
            'roles' => [1],
        ],
        [
            'title' => 'Activity',
            'icon' => 'tabler-activity',
            'route' => 'dashboard.activity.index',
            'active' => 'dashboard.activity.index',
            'sort' => 8,
            'roles' => [1],
        ],
        [
            'title' => 'Mailing Advantage',
            'icon' => 'tabler-mail',
            'route' => 'dashboard.mailingadvantage.index',
            'active' => 'dashboard.mailingadvantage.index',
            'sort' => 8,
            'roles' => [1],
        ],
    ];
